# Site settings
title: watchzerg's blog
email: watchzerg@gmail.com
description: >
  Well, this is my blog.
baseurl: ""
url: "http://watchzerg.github.io"
twitter_username: watchzerg
github_username:  watchzerg

# Build settings
markdown: kramdown	#使用kramdown做代码语法高亮
kramdown:
  input: GFM	#启用github的markdown语法
plugins:
  - jekyll-sitemap	#生成sitemap
  - jekyll-mentions	#允许"@somebody"
  - jemoji	#允许标签
