# Site settings
title: watchzerg's blog
email: watchzerg@gmail.com
description: > 
  Well, this is my blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://watchzerg.github.io" # the base hostname & protocol for your site
twitter_username: watchzerg
github_username:  watchzerg

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap